### ISSUE TITLE
DS3Helpers documentation / examples

### ISSUE THREAD

**Issue by stephenmcconnachie** [SpectraLogic/ds3_python3_sdk#51]
The DS3Helpers look very useful and interesting, but there doesn’t seem to be much documentation other than four examples (GET all from bucket, GET one object, PUT all, PUT one).

I would really like to use the end-to-end-CRC functionality so welcomed the latest PUT with MD5 example - can the Helpers also use checksum content header too? An example would be really useful!

Also the Helpers examples - such as https://github.com/SpectraLogic/ds3_python3_sdk/blob/master/samples/putting_one_file_in_directory.py  - refer to the ability to PUT / GET multiple objects with multi-threading possibly. Examples using the Helpers would be really useful, if possible.

**Comment by RachelTucker** [comment]
I'm sorry to say that the current implementation of the helpers do not support checksum calculations. That is a feature that could be added, but currently does not exist.

The helpers are defaulted to multi-thread processing 5 blobs per job at a time. That means 5 blobs are being put/get at all times so long as the job has at least 5 blobs to process. You can set a higher or lower value for `max_threads`, but be aware that more threads doesn't necessarily mean higher throughput since the threads themselves have overhead. The optimal number of threads will depend on the size of objects and the system your running your client on.

FYI in case you are not familiar with BP API, objects that are really large are broken up into multiple pieces which we call blobs. Blobs represent smaller units of data that the BP processes. The maximum size of blobs is typically 64GB. Objects that are smaller than that will be represented by a single blob. So a blob is usually between 1B - 64GB.

**Comment by stephenmcconnachie** [comment]
Thanks Rachel, no problem we'll build on the PUT-with-MD5 example, it's very clear.

One question though: is there a good practice methodology around the max size of a single BULK PUT Job? Should we be checking the cache's unused capacity each time and limiting the size of a PUT to avoid maxxing the cache? Is there a %-of-cache-unused that we should use?

**Comment by stephenmcconnachie** [comment]
That's really helpful, thank you so much.

**Comment by RachelTucker** [comment]
The feature checksum calculations has been added to the helpers in the latest release v5.4.1. The parameter `calculate_checksum` has been added to the `put_objects` and `put_all_objects_in_directory` calls. If you'd like checksums to be calculated, then set `calculate_checksum=True`. By default checkums will not be calculated for performance reasons.

Also, I've added documentation to the call [put_all_objects_in_directory](https://github.com/SpectraLogic/ds3_python3_sdk/blob/master/ds3/ds3Helpers.py#L246)

**Comment by stephenmcconnachie** [comment]
That's wonderful thank you!
